title: Default Page

tabs:
    content:
        label:
            en: Content
            el: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        contentblocks:
                            extends: fields/blocks

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
