title: Project Page

tabs:
    content:
        label:
            en: Content
            el: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        projectdate:
                            type: text
                            label: Year
                        text:
                            extends: fields/fulleditor
                        projectlink:
                            type: url
                            label: Project Link
                        gallery:
                            extends: fields/gallery
                        tags:
                            type: tags
                            label: Tags
                            options: query
                            query: page.siblings.pluck("tags", ",", true)
                            layout: list
          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
