title: Site

tabs:
    content:
        label:
            en: Content
            el: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                homepage:
                    headline: Home
                    type: pages
                    status: all
                    templates: home
                    max: 1
                projects:
                    headline: Projects
                    type: pages
                    status: all
                    templates: project
                    parent: site.find("work")
                blog:
                    headline: Posts
                    type: pages
                    status: all
                    templates: post
                    parent: site.find("blog")
                services:
                    headline: Services
                    type: pages
                    status: all
                    templates: default
                    parent: site.find("services")
                about:
                    headline: Pages
                    type: pages
                    status: all
                    templates: default
          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo:
        label: SEO
        icon: search
        columns:
          - width: 2/3
            sections:
                siteseo:
                    type: fields
                    fields:
                        sitetwitter:
                            type: text
                            label: Site Twitter Username
                        facebook:
                            type: url
                            label: Facebook Page
                        twitter:
                            type: url
                            label: Site Twitter Page
                        instagram:
                            type: url
                            label: Instagram Page
                        pinterest:
                            type: url
                            label: Pinterest Page
                        linkedin:
                            type: url
                            label: LinkedIn Page
